### Connexion via email
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "docjef62@gmail.com",
  "password": "Ecto19021986*"
}

###

### Mise à jour du mot de passe de l'utilisateur
PATCH http://localhost:3000/auth/update-password/130
Content-Type: application/json
Authorization: Bearer <token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAwLCJyb2xlIjozLCJpYXQiOjE3MzIyNzE2NTgsImV4cCI6MTczMjI3NTI1OH0.AxkdfUzASOgL483jV6IA5UH8v4TmE3PKb_MFRwgjViQ>

{
  "password": "jef123"
}

###

### Demande de réinitialisation de mot de passe
POST http://localhost:3000/auth/request-password-reset
Content-Type: application/json

{
  "email": "docjef62@gmail.com"
}

###

### Réinitialisation du mot de passe
POST http://localhost:3000/auth/reset-password
Content-Type: application/json

{
  "token": "61a2add3077434e568c768ce8a84e713dc2a4588c109b07083b24e6ad76134c5",
  "newPassword": "Ecto19021986***"
}
