### Récupérer tous les avis
GET http://localhost:3000/reviews

###

### Récupérer un avis par ID
GET http://localhost:3000/reviews/71

###

### Créer un nouvel avis (Utilisateur connecté)
POST http://localhost:3000/reviews
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAwLCJyb2xlIjozLCJpYXQiOjE3MzIyNzc4NTEsImV4cCI6MTczMjI4MTQ1MX0.yxmd_k4yp_TaQYgrCwwKtf7TsJw5U0TZ05wn73cyudE

{
  "note": 5,
  "comment": "Super expérience dans le parc !",
  "reservation_id": 4
}

###

### Supprimer un avis (Utilisateur connecté)
DELETE http://localhost:3000/reviews/54
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAwLCJyb2xlIjozLCJpYXQiOjE3MzIyNzc4NTEsImV4cCI6MTczMjI4MTQ1MX0.yxmd_k4yp_TaQYgrCwwKtf7TsJw5U0TZ05wn73cyudE

