@baseUrl = http://localhost:5000/api
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhbGljZS5kdXBvbnRAZXhhbXBsZS5jb20iLCJyb2xlSWQiOjEsImlhdCI6MTczODgyNzI3OCwiZXhwIjoxNzM4ODMwODc4fQ.oi_WNPH1laB5byqlsnf1HcyqIzX7CjEd2kSXhfwzyJI
@randomSuffix = {{Math.floor(Date.now()/1000)}}

### LOGIN ADMIN
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "alice.dupont@example.com",
  "password": "password1"
}

### OPTION CATEGORIES ###

### CREATE AN OPTION CATEGORY
POST {{baseUrl}}/categories?categoryType=option
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "OptCatq{{randomSuffix}}",
  "description": "Description for test option category",
  "is_default": false
}

### LIST ALL OPTION CATEGORIES
GET {{baseUrl}}/categories?categoryType=option
Authorization: Bearer {{adminToken}}

### GET OPTION CATEGORY BY ID
# Replace 1 with the actual ID of an existing option category
GET {{baseUrl}}/categories/5?categoryType=option
Authorization: Bearer {{adminToken}}

### UPDATE AN OPTION CATEGORY
# Replace 1 with the actual ID of an existing option category
PUT {{baseUrl}}/categories/5?categoryType=option
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "Updated Option Category {{randomSuffix}}",
  "description": "Updated description"
}

### DELETE AN OPTION CATEGORY
# Replace 1 with the actual ID of an existing option category
DELETE {{baseUrl}}/categories/5?categoryType=option
Authorization: Bearer {{adminToken}}

### EQUIPMENT CATEGORIES ###

### CREATE AN EQUIPMENT CATEGORY
POST {{baseUrl}}/categories?categoryType=equipment
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "EquipCzat{{randomSuffix}}",
  "description": "Description for test equipment category"
}

### LIST ALL EQUIPMENT CATEGORIES
GET {{baseUrl}}/categories?categoryType=equipment
Authorization: Bearer {{adminToken}}

### GET EQUIPMENT CATEGORY BY ID
# Replace 1 with the actual ID of an existing equipment category
GET {{baseUrl}}/categories/1?categoryType=equipment
Authorization: Bearer {{adminToken}}

### UPDATE AN EQUIPMENT CATEGORY
# Replace 1 with the actual ID of an existing equipment category
PUT {{baseUrl}}/categories/1?categoryType=equipment
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "Updated Equipment Category {{randomSuffix}}",
  "description": "Updated equipment description"
}

### DELETE AN EQUIPMENT CATEGORY
# Replace 1 with the actual ID of an existing equipment category
DELETE {{baseUrl}}/categories/1?categoryType=equipment
Authorization: Bearer {{adminToken}}