@baseUrl = http://localhost:5000/api
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhbGljZS5kdXBvbnRAZXhhbXBsZS5jb20iLCJyb2xlSWQiOjEsImlhdCI6MTczODgyNzI3OCwiZXhwIjoxNzM4ODMwODc4fQ.oi_WNPH1laB5byqlsnf1HcyqIzX7CjEd2kSXhfwzyJI
@randomSuffix = {{Math.floor(Date.now()/1000)}}

### LOGIN ADMIN
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "alice.dupont@example.com",
  "password": "password1"
}

### GET TOUTES LES ENTREPRISES
GET {{baseUrl}}/companies
Authorization: Bearer {{adminToken}}

### CRÉER UNE ENTREPRISE
POST {{baseUrl}}/companies
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "Société Test {{randomSuffix}}",
  "address": "123 Rue Exemple",
  "city": "Paris",
  "postalCode": "75000",
  "comments": "Entreprise de test",
  "establishmentType": "client potentiel",
  "organizationType": "Non spécifique",
  "numberOfCanteens": 0,
  "numberOfCentralKitchens": 0,
  "created_by": 1
}


### GET UNE ENTREPRISE PAR ID
GET {{baseUrl}}/companies/1
Authorization: Bearer {{adminToken}}

### METTRE À JOUR UNE ENTREPRISE
PUT {{baseUrl}}/companies/3
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "Société Test MAJ {{randomSuffix}}",
  "city": "Lyon"
}

### SUPPRIMER UNE ENTREPRISE
DELETE {{baseUrl}}/companies/2
Authorization: Bearer {{adminToken}}


### RÉASSIGNER UNE ENTREPRISE
PUT {{baseUrl}}/companies/4/reassign
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "newAssignedTo": 2
}

### RÉCUPÉRER MES ENTREPRISES
GET {{baseUrl}}/companies/my-companies
Authorization: Bearer {{adminToken}}

### ASSIGNER DES INTERLOCUTEURS À UNE ENTREPRISE
POST {{baseUrl}}/companies/1/assign-interlocutors
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "interlocutorIds": [4, 5]
}

### ASSIGNER UN UTILISATEUR À UNE ENTREPRISE
POST {{baseUrl}}/companies/1/assign-user
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "userId": 2
}

### DÉSASSIGNER UN UTILISATEUR D'UNE ENTREPRISE
PUT {{baseUrl}}/companies/1/unassign-user
Authorization: Bearer {{adminToken}}