@baseUrl = http://localhost:5000/api
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhbGljZS5kdXBvbnRAZXhhbXBsZS5jb20iLCJyb2xlSWQiOjEsImlhdCI6MTczNzU1MzgyMywiZXhwIjoxNzM3NTU3NDIzfQ.6mGOzpsqWqLPij3TC2zZQIbp0SvKdvvEtRks9R2tnx0
@randomSuffix = 

### LOGIN ADMIN
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "alice.dupont@example.com",
  "password": "password1"
}

### CRÉER UNE SIMULATION
POST {{baseUrl}}/simulations
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "userId": 1,
  "companyId": 1,
  "costPerDish": 3.0,
  "dishesPerDay": 1500,
  "wastePercentage": 24.0,
  "dailyProductionSavings": 302.4,
  "monthlyProductionSavings": 6048.0,
  "dailyWasteSavings": 672.0,
  "monthlyWasteSavings": 13440.0,
  "status": "en attente",
  "createdBy": 1
}

### GET TOUTES LES SIMULATIONS
GET {{baseUrl}}/simulations
Authorization: Bearer {{adminToken}}

### GET UNE SIMULATION PAR ID
GET {{baseUrl}}/simulations/1
Authorization: Bearer {{adminToken}}

### METTRE À JOUR UNE SIMULATION
PUT {{baseUrl}}/simulations/1
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "wastePercentage": 20.0,
  "notes": "Simulation mise à jour"
}

### SUPPRIMER UNE SIMULATION
DELETE {{baseUrl}}/simulations/:id
Authorization: Bearer {{adminToken}}
